version: 2.1

jobs:
  composer-install:
    docker:
      - image: php:8.1-cli
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Composer install"
          command: |
            apt update && DEBIAN_FRONTEND=noninteractive apt install -y git curl zip unzip

            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            php composer.phar install
      - persist_to_workspace:
          root: /root/project
          paths:
            - vendor/*

  phpunit:
    docker:
      - image: php:8.1-cli
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: "Run phpunit"
          command: |
            ./vendor/bin/phpunit tests

  lint:
    docker:
      - image: php:8.1-cli
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: "Run lint"
          command: |
            find src -name '*.php' -type f -exec php -l {} \;

workflows:
  test:
    jobs:
      - composer-install
      - lint
      - phpunit:
          requires:
            - composer-install
